In [1]:
import torch
import time
import numpy as np
device = torch.device("mps")
print(device)

mps


In [2]:
%%time
start_time = time.time()
# matrix operation
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time-start_time
print(f"{elapsed_time:.8f}")

0.00057292
CPU times: user 545 µs, sys: 503 µs, total: 1.05 ms
Wall time: 701 µs


In [4]:
%%time
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:8f}")

0.011344
0.067526
CPU times: user 1.08 s, sys: 207 ms, total: 1.29 s
Wall time: 1.44 s


In [5]:
# define a probability tensor
probabilities = torch.tensor([0.1, 0.9])

samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 0, 1, 1, 0, 1, 1, 1, 1, 1])


In [7]:
torch.cat((torch.tensor([1,2,3,4]), torch.tensor([5])), dim=0)

tensor([1, 2, 3, 4, 5])

In [8]:
torch.tril(torch.ones(5,5))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [9]:
torch.triu(torch.ones(5,5))

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [12]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [13]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [16]:
torch.zeros(2,3,4).transpose(0,2)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [17]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

torch.stack([tensor1, tensor2, tensor3])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

#### torch.nn module

In [20]:
import torch.nn as nn

sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False) # input = 3 output = 3
print(linear(sample))

tensor([-7.1842,  4.8275, -1.4049], grad_fn=<SqueezeBackward4>)


In [21]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


#### Embedding Vector

In [23]:
# Initialize the embedding layer
vocab_size = 10000
embedding_dim = 100

embedding = nn.Embedding(vocab_size, embedding_dim)

# create some input indices
input_indices = torch.LongTensor([1,5,3,2])

# Apply the embedding layer
embedding_output = embedding(input_indices)

print(embedding_output.shape)

torch.Size([4, 100])


In [26]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print(a @ b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [28]:
int_64 = torch.randint(1, (3,2)).float()
float_64 = torch.rand(2,3)

print(torch.matmul(int_64, float_64))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [31]:
a = torch.rand(2,3,5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [32]:
x = torch.tensor([-0.05], dtype=torch.float32)
y = F.sigmoid(x)
print(y)

tensor([0.4875])


In [33]:
x = torch.tensor([-0.05], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([-0.0500])


In [34]:
x = torch.tensor([1], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([0.7616])


In [35]:
x = torch.tensor([10], dtype=torch.float32)
y = F.sigmoid(x)
print(y)

tensor([1.0000])
